# Croatian Religious Terms - Regex Patterns for Text Matching
# Data frame with terms, roots, and regex patterns for religious content analysis

religious_terms <- data.frame(
  term = c(
    "biskup", "đakon", "blagoslov", "kardinal", "nadbiskup", "sveti otac",
    "papa", "vatikan", "bazilika", "križ", "nadbiskupija", "misa",
    "sakrament", "pavlin", "demon", "kršćanstvo", "stepinac", "katedrala",
    "euharistija", "biskupija", "relikvija", "svećenik", "provincijal", "franjevac",
    "kršćanin", "kapelan", "kler", "franjevci", "časna", "kaptol",
    "crkveni", "krunica", "redovnik", "redovnica", "krizma", "gospa",
    "pobožnost", "pontifikat", "sveto pismo", "katolička crkva", "katekizam", "vjeronauk",
    "teologija", "pričest", "duhovnost", "časna sestra", "papinski", "benediktinac",
    "evanđelje", "hodočasnik", "ispovijed", "dominikanac", "gvardijan", "teološki",
    "došašće", "sveto trojstvo", "liturgija", "posvećenje", "križni put", "sveta stolica",
    "trapist", "hodočašće", "enciklika", "pontif", "bezgrešno začeće", "nuncij",
    "monsinjor", "sveti križ", "isusovac", "presveti oltarski sakrament", "vatikanski", "časne sestre",
    "ispovjedaonica", "srce isusovo", "karmelićanin", "kapitul", "salezijanac", "opus dei",
    "duhovnik", "celibat", "rimokatolička crkva", "sveti red", "ukazanje", "korizma",
    "bolesničko pomazanje", "jezuiti", "papinstvo", "hostija", "vazmeno trodnevlje", "sveta krunica",
    "neokaljano srce", "zaređenje", "apostolsko nasljeđe", "nicejsko vjerovanje", "župnik"
  ),
  
  root = c(
    "biskup", "đakon", "blagoslov", "kardinal", "biskup", "otac",
    "pap", "vatikan", "bazilik", "križ", "biskup", "mis",
    "sakrament", "pavlin", "demon", "kršćan", "stepinac", "katedra",
    "euharistij", "biskup", "relikvij", "svećen", "provincial", "franjev",
    "kršćan", "kapelan", "kler", "franjev", "časn", "kaptol",
    "crkv", "krunic", "redovn", "redovn", "krizm", "gosp",
    "pobožn", "pontifikat", "pism", "crkv", "katekizm", "vjeronauk",
    "teolog", "pričest", "duhov", "sestr", "pap", "benediktin",
    "evanđelj", "hodočasn", "ispovijed", "dominikan", "gvardijan", "teolog",
    "došašć", "trojstv", "liturgij", "posveć", "put", "stolic",
    "trapist", "hodočašć", "enciklik", "pontif", "začeć", "nuncij",
    "monsinjor", "križ", "isusov", "sakrament", "vatikan", "sestr",
    "ispovijed", "isusov", "karmelić", "kapitul", "salezijan", "opus",
    "duhov", "celibat", "crkv", "red", "ukazan", "koriz",
    "pomazan", "jezuit", "pap", "hostij", "trodnevlj", "krunic",
    "src", "zared", "nasljeđ", "vjerovan", "župnik"
  ),
  
  regex = c(
    "biskup[aeiou]?[mnjstz]*",
    "đakon[aeiou]?[mnstz]*",
    "blagoslov[aeiou]?[jlmnst]*",
    "kardinal[aeiou]?[mnstz]*",
    "nadbiskup[aeiou]?[jmnstz]*",
    "sv(et[ieo]g?|ij)[aeiou]?\\s+ot[acš][aeiou]?[cmz]*",
    "pap[aeiou][jmnstz]*",
    "vatikan[aeiou]?[smz]*",
    "bazilik[aeiou][jmz]*",
    "križ[aeou]?[jmnvz]*",
    "nadbiskupij[aeiou][jmz]*",
    "mis[aeiou][jmz]*",
    "sakrament[aeiou]?[jmnstv]*",
    "pavlin[aeiou]?[cmz]*",
    "demon[aeiou]?[jmstz]*",
    "kršćan[aeiou]?[smstv]*",
    "stepinac[aeiou]?[cmz]*",
    "katedra[l][aeiou][jmz]*",
    "euharistij[aeiou][jmsz]*",
    "biskupij[aeiou][jmz]*",
    "relikvij[aeiou][jmz]*",
    "svećen[ijoš][kč][aeiou]?[jmnz]*",
    "provincial[aeiou]?[jmnstv]*",
    "franjev[acč][aeiou]?[cmz]*",
    "kršćan[ijaeo][nmz]*",
    "kapelan[aeiou]?[jmnstv]*",
    "kler[aeiou]?[jmnstv]*",
    "franjev[acč][aeio][jz]*",
    "časn[aeiou][jmstz]*",
    "kaptol[aeiou]?[jmstz]*",
    "crkv[aeiou]?[njmstz]*",
    "krunic[aeiou][jmsz]*",
    "redovn[io][kč][aeiou]?[jmz]*",
    "redovni[cč][aeiou][jmsz]*",
    "krizm[aeiou][jmsz]*",
    "gosp[aeiou][jmsz]*",
    "pobožn[io][jst][aeiou]?[jmstz]*",
    "pontifikat[aeiou]?[jmstz]*",
    "sv(et[ieo]g?|ij)[aeiou]?\\s+pism[aou][jmz]*",
    "katoli[čć][kč][aeiou]?[jmstz]*\\s+crkv[aeiou][jmsz]*",
    "katekizm[aeiou]?[jmstz]*",
    "vjeronauk[aeiou]?[jmstv]*",
    "teolog[ijoš][jk][aeiou]?[jmstz]*",
    "pričest[aeiou]?[jmstz]*",
    "duhov[nš][io][jst][aeiou]?[jmstz]*",
    "časn[aeiou]?[jmstz]*\\s+sestr[aeiou][jmsz]*",
    "papinsk[aeiou][jmstz]*",
    "benediktin[acč][aeiou]?[cmz]*",
    "evanđelj[aeiou][jmstz]*",
    "hodočasn[ijoš][kč][aeiou]?[jmz]*",
    "ispovijed[aeiou]?[jmstz]*",
    "dominikan[acč][aeiou]?[cmz]*",
    "gvardijan[aeiou]?[jmstz]*",
    "teološk[aeiou][jmstz]*",
    "došašć[aeiou][jmsz]*",
    "sv(et[ieo]g?|ij)[aeiou]?\\s+trojstv[aou][jmsz]*",
    "liturgij[aeiou][jmstz]*",
    "posveć[aeioš][njv][aeiou]?[jmstz]*",
    "križn[aeiou][jmstz]*\\s+put[aeiou]?[jmstz]*",
    "sv(et[aeiou]g?|ij)[aeiou]?\\s+stolic[aeiou][jmsz]*",
    "trapist[aeiou]?[jmstz]*",
    "hodočašć[aeiou][jmsz]*",
    "enciklik[aeiou][jmsz]*",
    "pontif[aeiou]?[jmstz]*",
    "bezgrešn[io][jmstz]*\\s+začeć[aeiou][jmsz]*",
    "nuncij[aeiou][jmsz]*",
    "monsinjor[aeiou]?[jmstz]*",
    "sv(et[ieo]g?|ij)[aeiou]?\\s+križ[aeiou]?[jmnvz]*",
    "isusov[acč][aeiou]?[cmz]*",
    "presv(et[ieo]g?|ij)[aeiou]?\\s+oltarsk[aeiou][jmstz]*\\s+sakrament[aeiou]?[jmstz]*",
    "vatikansk[aeiou][jmstz]*",
    "časn[aeiou][jmstz]*\\s+sestr[aeiou][jmsz]*",
    "ispovijeda?oni[cč][aeiou][jmsz]*",
    "sr[cč][aeiou]\\s+isusov[aeiou][jmstz]*",
    "karmelić[aeiou]?[nz][aeiou]?[jmstz]*",
    "kapitul[aeiou]?[jmstz]*",
    "salezijan[acč][aeiou]?[cmz]*",
    "opus\\s+dei",
    "duhovn[io][kč][aeiou]?[jmstz]*",
    "celibat[aeiou]?[jmstz]*",
    "rimokatolič[kč][aeiou]?[jmstz]*\\s+crkv[aeiou][jmsz]*",
    "sv(et[ieo]g?|ij)[aeiou]?\\s+red[aeiou]?[jmnstv]*",
    "ukazan[aeiou]?[jmstz]*",
    "koriz[mš][aeiou][jmsz]*",
    "bolesnič[kč][aeiou]?[jmstz]*\\s+pomazan[aeiou]?[jmstz]*",
    "jezuit[aeiou]?[jmstz]*",
    "papinstv[aou][jmsz]*",
    "hostij[aeiou][jmsz]*",
    "vazmen[aeiou][jmstz]*\\s+trodnevlj[aeiou][jmsz]*",
    "sv(et[aeiou]g?|ij)[aeiou]?\\s+krunic[aeiou][jmsz]*",
    "neokaljano\\s+sr[cč][aeiou]",
    "zaređ[aeioš][njv][aeiou]?[jmstz]*",
    "apostolsk[aeiou][jmstz]*\\s+nasljeđ[aeiou][jmstz]*",
    "nicejsk[aeiou][jmstz]*\\s+vjerovan[aeiou]?[jmstz]*",
    "župn[io][kč][aeiou]?[jmstz]*"
  ),
  
  stringsAsFactors = FALSE
)

# Export the data frame
religious_terms
